source 'https://rubygems.org'

gem 'rack-cors'
gem 'grape'
gem 'grape-entity'
gem 'data_mapper'

group :development, :test do
  gem 'rspec'
  gem 'rack-test'
  gem 'sqlite3'
  gem 'dm-sqlite-adapter'
end

group :production do
  gem 'pg'
  gem 'dm-postgres-adapter'
end
