source 'https://rubygems.org'

gem 'rack-cors', '~> 0.4.0'
gem 'grape', '~> 0.18.0'
gem 'grape-entity', '~> 0.5.1'
gem 'data_mapper', '~> 1.2.0'
gem 'dm-timestamps', '~> 1.2.0'
gem 'omniauth-facebook'

group :development, :test do
  gem 'rspec', '~> 3.5.0'
  gem 'rack-test', '~> 0.6.3'
  gem 'sqlite3', '~> 1.3.12'
  gem 'dm-sqlite-adapter', '~> 1.2.0'
end

group :production do
  gem 'pg', '~> 0.19.0'
  gem 'dm-postgres-adapter', '~> 1.2.0'
end
